EDU-2415: Updates contributor instructions
Also:
* Adds language for `temporal`, `temporal activity`, `temporal activity
  complete` and `temporal activity fail`.

NOTES

* I'm a little confused by the inconsistency of punctuation.
* How wordy do you want the command-line usage to be? There's already an
  overwhelming amount of "wall of text".

I was thinking more:

```
* `--env` (string) - Active environment name. Default: default. Env: TEMPORAL_ENV.
* `--env-file` (string) - Path to environment settings file (defaults to `$HOME/.config/temporalio/temporal.yaml`).
* `--log-level` (string-enum) - Log level. Default is "info" for most commands and "warn" for `server start-dev`.
  Options: debug, info, warn, error, never. Default: info.
* `--log-format` (string) - Log format. Options are "text" and "json". Default is "text".
* `--output`, `-o` (string-enum) - Non-logging data output format. Options: text, json, jsonl,
  none. Default: text.
* `--time-format` (string-enum) - Time format. Options: relative, iso, raw. Default: relative.
* `--color` (string-enum) - Output coloring. Options: always, never, auto. Default: auto.
* `--no-json-shorthand-payloads` (bool) - Show all payloads as raw, even if they are JSON. Default: false.
```

over

```
* `--env` (string) - Read additional options from the `ENV` environment. (See "temporal env --help" for more about environments.) Default: default. Env: TEMPORAL_ENV.
* `--env-file` (string) - Read/store per-environment configuration in `PATH` (defaults to "$HOME/.config/temporalio/temporal.yaml").
* `--log-level` (string-enum) - Log level. Default is "info" for most commands and "warn" for the development server.
  Options: debug, info, warn, error, never. Default: info.
* `--log-format` (string) - Emit log messages in "text" or "json" format. Default is "text".
* `--output`, `-o` (string-enum) - Emit output in the `FMT` format. Does not affect logs; use --log-format instead. Options: text, json, jsonl,
  none. Default: text.
* `--time-format` (string-enum) - Emit timestamps in the `FMT` format. Options: relative, iso, raw. Default: relative.
* `--color` (string-enum) - Colorize output. Does not affect logs. Options: always, never, auto. Default: auto.
* `--no-json-shorthand-payloads` (bool) - Show all payloads as raw payloads even if they are JSON.
```

ISSUES

1. There's no way to bundle the `temporal` options, which are
   imported elsewhere. They have to be there and they are
   distracting, and contribute to overwhelmed users.

2. Even though I set a description for complete and fail, they are not shown

   cli% ./temporal activity complete
   Error: required flag(s) "activity-id", "result", "workflow-id" not set
   Usage:
     temporal activity complete [flags]

   Ditto for temporal activity fail.