Fix username in default reason string (#1002)
## What was changed
Use username in default reason when username is available. 

## Why?
It's what was intended; the code just had a typo.

## How was this tested:

1. Contains a test of termination
2. Manually tested termination of standalone activity

```
$ temporal activity terminate --activity-id standalone_activity_helloworld_ActivityID
Activity terminated

$ temporal activity result -a standalone_activity_helloworld_ActivityID
Results:
  Status   FAILED
  Failure
    Message: Requested from CLI by dan
Error: activity failed
```

---------

Co-authored-by: Alex Stanfield <13949480+chaptersix@users.noreply.github.com>